version: '3.1'

networks:
  backpackbuddy:
    driver: bridge

services:
  app:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    env_file: .env
    command: npm start
    restart: unless-stopped
    networks:
      - backpackbuddy
