version: '3.1'

networks:
  backpackbuddy:
    driver: bridge

services:
  app:
    image: node:16-alpine
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    env_file: .env
    command: sh -c 'npm i --force; npm run build; npm start'
    restart: unless-stopped
    networks:
      - backpackbuddy
