export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const DESTINATION_LIST_FETCH = 'DESTINATION_LIST_FETCH';
export const DESTINATION_LIST_LOAD_MORE = 'DESTINATION_LIST_LOAD_MORE';
export const DESTINATION_LIST_LOADING = 'DESTINATION_LIST_LOADING';
export const DESTINATION_LIST_SET_FILTER = 'DESTINATION_LIST_FILTER';
